### PR TITLE
Issue.#89.crafter creation

### LINKED ISSUE #128: [BUG] - Use the same constant for select a machine
**Describe the bug**
Currently we are using the same constant for select a machine type, this is producing that every machine created with this selecting point to the same reference. This produce that, for example, if you change the material of a starter, each starter in the grid going to change his respective material 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by FedeLochbaum**
# Pull Request Template

## Description

This pr allow create a crafter machine selecting a recipe, the recipes are created in the Game.constant file.
Moreover, this pr fix a specific issue, we had setting the same type constant for each machine type, this did that when a machine changed the type or the material, every machine with that type ( in redux) was changed.
CrafterCreation

Fixes #128  #127 #89 

For merge this pr, first we need that @LaimeJesus merge his fix about have `machineSelected` as prop in Game
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] `yarn test`
- [ ] `yarn cypress:run`
- [ ] `yarn storybook`
- [ ] `yarn start`

**Test Configuration**:
* OS: 
* Browser: 
* Hardware: 

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/components/Machine/CrafterMachine/CrafterMachine.jsx [hunk 1]
```diff
@@ -1,16 +1,106 @@
...
-import { crafterMachine as machine, areEquals } from '../../Game/Game.constants'
+import './CrafterMachine.css'
+import { crafterMachine as machine, recipes } from '../../Game/Game.constants'
+
+class CrafterMachine extends Component {
+  constructor(props) {
+    super(props)
+    this.state = {
+      open: false,
+      recipeSelected: recipes[0],
```
Comment (LaimeJesus) [inline src/components/Machine/CrafterMachine/CrafterMachine.jsx]: I think It is not a good idea to depend on global variables(DI pls).
A good practice for me would be to pass the `recipes` as props, so we would be able to change that parameter when we instantiate that component(in a test for example/mocking).

File: src/components/Game/Game.constants.js [hunk 2]
```diff
@@ -149,6 +150,126 @@ const ironMaterial = {
...
+  image: billon,
+  price: 20,
+}
+
+const whiteGoldRecipe = {
+  name: 'White Gold Recipe',
+  necessaryMaterials: [
+    {
+      material: goldMaterial,
+      count: 2,
```
Comment (LaimeJesus) [inline src/components/Game/Game.constants.js]: I think count is not a `happy` name for that property, quantity, quantityNeeded or countNeeded, would be a better name

File: src/components/Game/Game.constants.js [hunk 3]
```diff
@@ -149,6 +150,126 @@ const ironMaterial = {
...
+    {
+      material: silverMaterial,
+      count: 1,
+    },
+    {
+      material: copperMaterial,
+      count: 1,
+    },
+  ],
+  currencyCost: 0,
```
Comment (LaimeJesus) [inline src/components/Game/Game.constants.js]: we should keep a standard name for pricing/buying/etc, It should be price or we should change the machine price into currencyCost.

File: src/components/Machine/CrafterMachine/CrafterMachine.jsx [hunk 4]
```diff
@@ -1,16 +1,106 @@
...
+import Popper from '@material-ui/core/Popper'
+import Fade from '@material-ui/core/Fade'
+import Paper from '@material-ui/core/Paper'
+import { Button } from '@material-ui/core'
 import '../Machine.css'
-import { crafterMachine as machine, areEquals } from '../../Game/Game.constants'
+import './CrafterMachine.css'
+import { crafterMachine as machine, recipes } from '../../Game/Game.constants'
+
+class CrafterMachine extends Component {
```
[the remark this answers is not in the document]
Comment (FedeLochbaum) [reply src/components/Machine/CrafterMachine/CrafterMachine.jsx]: Is right that are very similar but i am not sure, i think that if we create a generic component for those, doesn't util for future. I would let this as a technical debt

File: src/components/Machine/CrafterMachine/CrafterMachine.jsx (hunk 1 above)
Comment (FedeLochbaum) [reply src/components/Machine/CrafterMachine/CrafterMachine.jsx]: mmmm i think that is more specify of this machines, also, why pass as props ? the recipes never change. Maybe, if we think and discuss a good way, it could be possible, yes.
